

services:
  # ACA-Py agent - using pre-built image
  aries-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - "8031:8031"
      - "8030:8030"
    command: >
      start
        --admin 0.0.0.0 8031
        --admin-api-key adminkey
        --endpoint http://aries-agent:8030
        --inbound-transport http 0.0.0.0 8030
        --outbound-transport http
        --label "Academic Credentials Issuer"
        --wallet-type indy
        --wallet-name issuer_wallet
        --wallet-key issuer_key
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{"url":"wallet-db:5432","max_connections":5}'
        --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'
        --auto-provision
        --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis
        --log-level info
    environment:
      - ACAPY_ENDPOINT=http://aries-agent:8030
      - ACAPY_LABEL=Academic Credentials Issuer
      - ACAPY_ADMIN_API_KEY=adminkey
      - ACAPY_ADMIN=0.0.0.0 8031
      - ACAPY_WALLET_TYPE=indy
      - ACAPY_WALLET_NAME=issuer_wallet
      - ACAPY_WALLET_KEY=issuer_key
      - ACAPY_WALLET_STORAGE_TYPE=postgres_storage
      - ACAPY_WALLET_STORAGE_CONFIG={"url":"wallet-db:5432","max_connections":5}
      - ACAPY_WALLET_STORAGE_CREDS={"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}
      - ACAPY_AUTO_PROVISION=true
      - ACAPY_LOG_LEVEL=info
      - ACAPY_GENESIS_URL=http://dev.greenlight.bcovrin.vonx.io/genesis
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8031"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aries-network
    depends_on:
      - wallet-db

  # Wallet database
  wallet-db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    networks:
      - aries-network

  # Ganache - Ethereum blockchain
  ganache:
    image: trufflesuite/ganache-cli:latest  # Try the CLI version instead
    ports:
      - "8545:8545"
    # Update command format to match the container's expected syntax
    command: >
      --gasLimit 8000000000000
      --deterministic
      --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      --networkId 1337
      --chainId 1337
      --host 0.0.0.0
    networks:
      - aries-network

  # Ethereum Bridge service
  ethereum-bridge:
    build:
      context: ../ethereum-bridge
      dockerfile: Dockerfile
    image: docker-ethereum-bridge:latest
    ports:
      - "3000:3000"
    environment:
      - ETH_RPC_URL=http://ganache:8545
      - ARIES_ADMIN_URL=http://aries-agent:8031
      - ARIES_ADMIN_API_KEY=adminkey
    networks:
      - aries-network
    depends_on:
      - ganache
      - aries-agent
    volumes:
      - ../ethereum-bridge:/app
      - /app/node_modules
      - "../smartcontracts/contracts:/app/src/contracts"

  # Backend service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ARIES_ADMIN_URL=http://aries-agent:8031
      - ARIES_ADMIN_API_KEY=adminkey
      - BRIDGE_URL=http://ethereum-bridge:3000
      - DEBUG=true
    networks:
      - aries-network
    depends_on:
      aries-agent:
        condition: service_healthy
      ethereum-bridge:
        condition: service_started
    volumes:
      - /app/node_modules

volumes:
  wallet-db-data:

networks:
  aries-network:
    driver: bridge