services:
  # ACA-Py agent - using pre-built image
  aries-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - "8031:8031"
      - "8030:8030"
    command: >
      start
        --admin 0.0.0.0 8031
        --admin-api-key adminkey
        --endpoint http://aries-agent:8030
        --inbound-transport http 0.0.0.0 8030
        --outbound-transport http
        --label "Academic Credentials Issuer"
        --wallet-type indy
        --wallet-name issuer_wallet
        --wallet-key issuer_key
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{"url":"wallet-db:5432","max_connections":5}'
        --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}'
        --auto-provision
        --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis
        --log-level info
    networks:
      - aries-network
    depends_on:
      - wallet-db

  # Wallet database
  wallet-db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    networks:
      - aries-network

  # Ganache - Ethereum blockchain
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: >
      --gasLimit 8000000000000
      --deterministic
      --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      --networkId 1337
      --chainId 1337
      --host 0.0.0.0
    networks:
      - aries-network

  # Backend service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ARIES_ADMIN_API_URL=http://aries-agent:8031
      - ARIES_ADMIN_URL=http://aries-agent:8031
      - ARIES_ADMIN_API_KEY=adminkey
      - ETH_RPC_URL=http://ganache:8545
      - DEBUG=true
    networks:
      - aries-network
    depends_on:
      - aries-agent
      - ganache
    volumes:
      - /app/node_modules

volumes:
  wallet-db-data:

networks:
  aries-network:
    driver: bridge